apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: christman-runner

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: christman-runner
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: argocd

images:
  - name: harbor.homalab.com/christman/christman-runner
    newTag: latest
